### ISSUE TITLE
Errors with second device

### ISSUE THREAD

**Issue by durosity** [tenallero/Indigo-ThinkingCleaner#2]
Hey,

I've recently started getting errors with my upstairs thinking cleaner device.  I've tried deleting all devices and re-discovering them and when I do that I get the following errors:

`1 Dec 2018 at 01:18:46
   ThinkingCleaner                 Discovering devices in this LAN ...
   ThinkingCleaner                 Created new device folder "ThinkingCleaner"
   ThinkingCleaner Debug           Upstairs: Requesting status.
   ThinkingCleaner Debug           Upstairs: Status received.
   ThinkingCleaner Error           Error in plugin execution MenuAction:

Traceback (most recent call last):
  File "plugin.py", line 1331, in menuDeviceDiscovery
  File "plugin.py", line 435, in deviceDiscover
  File "plugin.py", line 471, in createdDiscoveredDevice
  File "plugin.py", line 214, in addDeviceToList
  File "plugin.py", line 838, in sensorUpdateFromRequest
  File "plugin.py", line 1043, in sensorUpdate
KeyError: ('cleaning',)

   ThinkingCleaner                 Created new device "Upstairs" of type "thinkingcleaner"`

Now at this point it doesn't discover my downstairs one which works just fine if I manually add it to Indigo.  As best I can tell both the devices are identical and running the same firmware (1.0.69-310C-EU)

Any ideas?

**Comment by durosity** [comment]
Oh and for reference this is the log I get when it's setup with the one that works:

`   Reloading plugin "ThinkingCleaner 1.0.18"
   Stopping plugin "ThinkingCleaner 1.0.18" (pid 58050)
   ThinkingCleaner Debug           stopConcurrentThread called
   ThinkingCleaner Debug           Exited polling thread
   ThinkingCleaner Debug           stopConcurrentThread called
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Stoping device
   ThinkingCleaner Debug           shutdown called
   Stopped plugin "ThinkingCleaner 1.0.18"
   Starting plugin "ThinkingCleaner 1.0.18" (pid 93014)
   Started plugin "ThinkingCleaner 1.0.18"
   ThinkingCleaner Debug           startup called
   ThinkingCleaner Debug           WebHook: Starting HTTP listener on port 8686
   ThinkingCleaner Debug           KeepAlive: New thread.
   ThinkingCleaner Debug           KeepAlive: Starting daemon
   ThinkingCleaner Debug           Plugin version detected: 1.0.18
   ThinkingCleaner Debug           Current version is: 1.0.18
   ThinkingCleaner Debug           Getting latest release from tenallero/Indigo-ThinkingCleaner...
   ThinkingCleaner Debug           GET /repos/tenallero/Indigo-ThinkingCleaner/releases/latest
   ThinkingCleaner Debug           Latest release is: 1.0.17
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Starting device
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Requesting status.
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Status received.
   ThinkingCleaner Debug           Starting polling thread
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Requesting status.
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Status received.
`

**Comment by durosity** [comment]
And if I change that working device's IP address to that of the upstairs one:

   ThinkingCleaner Error           Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1179, in deviceUpdated
  File "plugin.py", line 196, in deviceStartComm
  File "plugin.py", line 214, in addDeviceToList
  File "plugin.py", line 838, in sensorUpdateFromRequest
  File "plugin.py", line 1043, in sensorUpdate
KeyError: ('cleaning',)


1 Dec 2018 at 01:31:29
   ThinkingCleaner                 sent "Dining Room - Downstairs Roomba" status request
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Requesting status.
   ThinkingCleaner Debug           Dining Room - Downstairs Roomba: Status received.
   ThinkingCleaner Error           Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 1312, in actionControlDimmerRelay
  File "plugin.py", line 1043, in sensorUpdate
KeyError: ('cleaning',)
